name: paypal_flutter
description: "Package that allows integration of PayPal payment gateway in Flutter applications."
version: 0.0.1
homepage: https://github.com/rojanshr1996/paypal_flutter

environment:
  sdk: ^3.7.0-323.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: 

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
  
license: MIT